### ISSUE TITLE
Sails v1

### ISSUE THREAD

**Issue by aleexkj** [malpercio/sails-hook-fireline#8]
Should attempt to load sequelize with configuration from `sails.config.datastores` or `sails.config.connections`

**Comment by malpercio** [comment]
Ill look into it. Expect it by tomorrow.

**Comment by malpercio** [comment]
#03d0904f95c4b631d0586c6a4434e5bb655cd286

**Comment by madlemur** [comment]
This loads the configuration, but the system references that object more than once. The same ```sails.config.connections``` vs. ```sails.config.datastores``` logic needs to be put in place in ```lib/initialize.js``` and ```lib/fx/load_hooks.js```, as both reference that config object.
